List<String> availableTagovi = [
  "Doručak",
  "Ručak",
  "Večera",
  "Užina",
  "Zdravo",
  "Brza hrana",
  "Pite",
  "Salata",
  "Meso",
  "Piletina",
  "Jagnjetina",
  "Govedina",
  "Svinjetina",
  "Riba",
  "Bez glutena",
  "Bez laktoze",
  "Desert",
  "Torta",
  "Kolač",
  "Grilovano",
  "Prženo",
  "Vegansko",
  "Kuhano",
  "Vegetarijansko",
  "Italijanska kuhinja",
  "Francuska kuhinja",
  "Kineska kuhinja",
  "Indijska kuhinja",
  "Meksička kuhinja",
  "Japanska kuhinja",
  "Turska kuhinja",
  "Grčka kuhinja",
  "Španska kuhinja",
  "Njemačka kuhinja",
  "Britanska kuhinja",
  "Tradicionalno",
  "Prilog",
  "Sos",
  "Predjelo",
  "Voćno",
  "Sladoled",
  "Bez šećera",
  "Čaj",
  "Kafa",
  "Sendvič",
  "Koktel",
  "Tijesto",
  "Tjestenina",
  "Slatko",
  "Slano",
  "Keks",
  "Šlag",
  "Poslastica",
  "Zimnica",
];
